name: h1ghway
favicon: null
layout_spectrum: 0.33510019443929195
typography_spectrum: 0.52883
title: h1ghway
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#636466'
    - '#ffffff'
    - '#fff200'
    - '#989442'
    - '#b1b2b3'
  brandStrength: 0.3125
  lightness: 0.8507624545600265
  saturation: 0.897033462068066
  rhythmicContrast: 0.4550274640787393
purpose: []
